// <auto-generated />
using System;
using MachineSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineSystem.Migrations
{
    [DbContext(typeof(CoordinateContext))]
    partial class CoordinateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("MachineSystem.PointCoordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("time")
                        .HasColumnType("TEXT");

                    b.Property<double>("x")
                        .HasColumnType("REAL");

                    b.Property<double>("y")
                        .HasColumnType("REAL");

                    b.Property<double>("z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PointCoordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
